services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Application\Controller\:
        resource: '../../../src/Application/Controller/*'
        
    controller.landing:
        alias: 'Application\Controller\Landing'

    controller.recepie:
        alias: 'Application\Controller\RecepiesController'

