# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
recepies:
    path: /{resource}{slash}
    requirements:
        resource: "recepie"
        slash: "[/]{0,1}"
    methods: [GET,POST,DELETE,PUT]

actionincluded:
    path: /{resource}/{action}
    requirements:
        resource: "recepie"
        slash: "[/]{0,1}"
    methods: [GET,POST,DELETE,PUT]